# Generated by Django 2.0 on 2018-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_balance', models.IntegerField(default=1000)),
            ],
        ),
    ]
