# Generated by Django 2.0 on 2018-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=200)),
                ('previous_hash', models.CharField(max_length=200)),
                ('current_hash', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
            ],
        ),
    ]
